# Generated by Django 3.0.7 on 2020-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prod_price',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.CharField(default='no image', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='no prod', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='image_link',
            field=models.CharField(default='no image', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
